### ISSUE TITLE
go get installation from source code seems to fail

### ISSUE THREAD

**Issue by pcm32** [involucro/involucro#68]
Hi there!

I'm trying to source compile involucro on macOS High Sierra, after a fresh go install from brew (installs version 1.10.3 of go) and setting the $GOPATH var to ~/.go.

Following the instructions on your README I get:

```
go get -v github.com/involucro/involucro
github.com/involucro/involucro (download)
package github.com/involucro/involucro: no Go files in /Users/pmoreno/.go/src/github.com/involucro/involucro
(mulled) C02WF18BHV2H:bioconda-recipes pmoreno$ ls ~/.go/src/github.com/involucro/involucro/
.git/             .travis.yml       LICENSE           README.md         appveyor.yml      cmd/              examples/         integrationtest/  invfile.lua       versioninfo.json  
.gitignore        CONTRIBUTING.md   NOTICE.md         app/              auth/             docs/             ilog/             internal/         vendor/
```

As you can see the go download does work, but for some reason it doesn't like the directory structure presented by the repo...

I'm trying to compile this as using the static version is throwing an error reported here:
https://github.com/galaxyproject/galaxy-lib/issues/124

Thanks!

**Comment by pcm32** [comment]
Now that macOS is supported on travis, it might be a good idea to add the involucro compilation there for macOS as well (besides windows and linux).

**Comment by pcm32** [comment]
Ping @bgruening

**Comment by pcm32** [comment]
To make it work, I went inside the involucro folder and execute `go build cmd/involucro/main.go` and then renamed the `main` binary produced and left it somewhere in the path. Is this enough or the package also requires other go source I'm not including? That seems to be picked up fine by galaxy-lib, from where I'm using this. Thanks!

**Comment by thriqon** [comment]
Yep, that's  a documentation bug. Will update the `README` soon, on the meantime you can `go get github.com/involucro/involucro/cmd/involucro`.

Regarding macos: There is a release binary for darwin: https://github.com/involucro/involucro/releases/download/latest/involucro.darwin Unfortunately, I can't really test it for lack of hardware.

**Comment by thriqon** [comment]
If you want to talk about involucro and how you use it or if you encounter any problems, I'd be happy to help and learn about how it is used.

**Comment by pcm32** [comment]
Thanks Jonas. I needed to compile as I was getting what seems to be a memory allocation error when using the compiled binary available in the release page (see link of issue I mentioned in the beginning).
