### ISSUE TITLE
Image created from r-seurat bioconda package through error on runtime

### ISSUE THREAD

**Issue by pcm32** [involucro/involucro#70]
Hi there!

We used involucro through galaxy-lib to create a container for [r-seurat-scripts](https://github.com/ebi-gene-expression-group/bioconda-recipes/tree/r-seurat-workflow/recipes/r-seurat-scripts), which is mainly based on r-seurat and r-optparse (from bioconda). When we try to execute one of our script (shebanged with Rscript) we get the following error when running inside the container:

```
/usr/local/lib/R/bin/exec/R: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
```

Anything in addition that we should be adding to our bioconda package? It seems to work fine when using it as a conda package not through the container.

Container is here if you want to inspect `quay.io/ebigxa/r-seurat-scripts:0.0.1--0`.

Error comes when, inside the container, executing: `read-10x.R`.

Thanks!

**Comment by bgruening** [comment]
This has nothing to do with incolucro, but more likely because of broken conda recipes. Do you have the logs from your mulled-build run?

**Comment by pcm32** [comment]
Could it be that I still had the r channel on the last time I run it? Will gist the logs. Thanks @bgruening!

**Comment by pcm32** [comment]
Here are the logs, thanks!
https://gist.github.com/pcm32/8c104b80ae93400c98057415707cdaad

**Comment by pcm32** [comment]
Re-trying in the meantime with R channel removed

**Comment by pcm32** [comment]
Problem persists after removing R channel (and doing a `conda build purge`), rebuilding container, pushing it and pulling it again.

**Comment by pcm32** [comment]
I've noticed that conda on the host machine and inside involucro are still using some different versions of the same packages, for instance:

in the host machine (conda build)
```
    r-base:           3.4.1-4               conda-forge
    r-base64enc:      0.1_3-r3.4.1_0        conda-forge
    r-bh:             1.66.0_1-r3.4.1_0     conda-forge
    r-bindr:          0.1.1-r3.4.1_0        conda-forge
```

whereas involucro shows:
```
[Jul  9 13:43:56] SOUT r-base:           3.4.1-4                 conda-forge
[Jul  9 13:43:56] SOUT r-bh:             1.62.0_1-r3.4.1_0
[Jul  9 13:43:56] SOUT r-bindr:          0.1-r3.4.1_0
```

is there some conda-involucro cache I should be getting rid of from when I was using the R channel? Thanks!

**Comment by bgruening** [comment]
Can you give me a new log? In the old one the problem was the `r` channel.

**Comment by pcm32** [comment]
This is the last one... I included the test that I know it generates the libconv issue: `read10x.R --help`
https://gist.github.com/pcm32/f6b61bee30ed1f433205ad0335b05d2f
Thanks!

**Comment by pcm32** [comment]
Although my previous comment (packages with different versions inside and outside of involucro building) was already without the R channel. I wonder if somehow some cache is left within involucro-retrieved conda packages that might be persisting the issue.

**Comment by pcm32** [comment]
I have been looking on involucro for a way of cleaning up cached conda packages, but haven't found anything. I'm always doing `conda build purge` at the end of the runs, but it only affects the system conda, not whatever is being used by involucro.

**Comment by bgruening** [comment]
Mh, it seem like the channel order is wrong. Fyi in Conda-land the channel order is very important and it seems `defaults` has a higher priority than bioconda, which should not happe. Can you try:

 --extra-channel file://miniconda/conda-bld/,bioconda,conda-forge,defaults

The priority needs to be: https://bioconda.github.io/#set-up-channels

**Comment by pcm32** [comment]
ahhhh!! will try that straight away, thanks!

**Comment by pcm32** [comment]
It worked! thanks!
